netresearch/t3x-rte_ckeditor_image

Resources/Public/JavaScript/Plugins/typo3image.js
=> [BUGFIX] Use $.extend for compatibility with IE11

Classes/Controller/ImageLinkRenderingController.php
=> [BUGFIX] Use proper condition for empty DomDocuments

Classes/Database/RteImagesSoftReferenceIndex.php, Configuration/TCA/Overrides/tt_content.php, ext_localconf.php
*  Add RteImagesSoftReferenceIndex (this was copied from sgalinski/tinymce4-rte)
*  Configure RTE images for soft reference index
Right now only tt_content.bodytext but the same logic can be applied
to any other RTE field.
=> [TASK] #45: Update image reference index

Classes/Controller/ImageLinkRenderingController.php
Problem when a single quote exists in html atrribute
Closes #73
=> [Classes] Fix attrSearchPattern ImageLinkRendering 

Resources/Public/JavaScript/Plugins/typo3image.js
resolve #78
Update image information and regenerate processed images when editor is initialised.
=> [FEAT] #78: Regenerate missing processed images

Resources/Public/JavaScript/Plugins/typo3image.js
Resolve #69 
Fix zoom feature.
Consider override checkbox for title and alt attributes.
=> [BUGFIX] #69: Remove zoom attributes when checkbox is disabled

ext_localconf.php
=> [BUGFIX] #71: Fix tsconfig includes

Classes/Controller/SelectImageController.php, LICENSE, Resources/Public/JavaScript/Plugins/typo3image.js
Merged master into dev-10 and resolved conflicts.
=> Dev typo3 10.x

Configuration/TypoScript/ImageRendering/setup.txt
fixes https://github.com/netresearch/t3x-rte_ckeditor_image/issues/112
=> [BUGFIX] use parseFunc_RTE for processing

Classes/Controller/SelectImageController.php, README.md, Resources/Private/Language/locallang_be.xlf, Resources/Public/JavaScript/Plugins/typo3image.js
Fix #88 
Optional class for each image.
=> [FEAT] #88: Add custom class field for each image

Classes/Controller/ImageLinkRenderingController.php, Classes/Controller/ImageRenderingController.php, README.md
fixes #82 
Add TYPO3 image lazyload support (native browser lazyload attribute).
=> [FEAT] #82: TYPO3 lazyload support

composer.json
Tested with TYPO3 v11.1, it's working well :)
=> [TASK] Allow installation on TYPO3 v11

Resources/Public/JavaScript/Plugins/typo3image.js
jQuery wasn't always available when running image script. This crashed the whole editor functionality. 
Fixes #122
=> [BUGFIX] #122: Fix jquery requirement to not crash the ckeditor

Classes/Controller/ImageLinkRenderingController.php
RTE Images within links shouldn't be wrapped by an p tag, that's not valid HTML.
Another solution would be disabling the wrapper via TS Setup: #129 
Fixes #112
=> [BUGFIX] #112: Remove wrapping p-tag from images

Resources/Public/JavaScript/Plugins/typo3image.js
Based on solution by @YolfTypo3 in #173 
Fixes #173
=> [BUGFIX] Preserve important image attributes on initialization

Classes/Database/RteImagesDbHook.php, README.md, ext_conf_template.txt
It can now be configured if external images should be fetched in the extension configuration.
Resolves: #189
Related: #190
=> [BUGFIX] Make fetching of external image configurable

Classes/Controller/ImageRenderingController.php
A couple more of undefined array key accesses which cause issues with PHP 8+.
=> Fix undefined array key access

Classes/Database/RteImagesDbHook.php
The previewimages will also be generated in backend view.
Resolves: #199
=> [BUGFIX] Regenerate images in backend view

README.md
Just some TYPO3 badge examples.
Request for comments.
=> add TYPO3 badges to README

Classes/Controller/ImageRenderingController.php, Classes/Controller/SelectImageController.php, Classes/Database/RteImagesDbHook.php, Classes/EventListener/RteConfigurationListener.php, Configuration/JavaScriptModules.php, Configuration/RTE/Plugin.yaml, Configuration/Services.yaml, Configuration/TCA/Overrides/sys_template.php, Configuration/TCA/Overrides/tt_content.php, Configuration/TypoScript/ImageRendering/setup.typoscript, Resources/Public/JavaScript/Plugins/typo3image.js, composer.json, ext_emconf.php, ext_localconf.php
This pull request provides support for TYPO3 v12
Fixes https://github.com/netresearch/t3x-rte_ckeditor_image/issues/234
=> TYPO3 v12 Support

Classes/Database/RteImagesDbHook.php
resolves https://github.com/netresearch/t3x-rte_ckeditor_image/issues/261
=> [BUGFIX] prevent open_basedir warnings

Resources/Public/JavaScript/Plugins/typo3image.js
Fix missing class attribute in <img>
Closes #266
=> Apply class to <img>

README.md
**Closing issues**
Closes #288
=> Update README.md for V12
