netresearch/t3x-rte_ckeditor_image

- composer.json
In order to allow single packages for a project
> Depend on typo3/cms-core instead of typo3/cms

- Resources/Public/JavaScript/Plugins/typo3image.js
- composer.json
Introduce a separate command for the context menu, that tries to find
the image in the current selection, to make the properties dialog appear,
even if the editor selects the table cell, because the image is the only
element in the cell.
Set branch alias correctly to 8.x-dev.
> [BUGFIX] `Image properties` not working inside table cell

- Resources/Public/JavaScript/Plugins/typo3image.js
* use existing `attributes` variable when returning the attributes from
the editing dialog
> [BUGFIX] Avoid loosing existing attributes when editing image

- Resources/Public/JavaScript/Plugins/typo3image.js
When calculating ratio, max width and height the original images data
must be used to allow scaling images to their originals maximum size.
> [BUGFIX] Use original files width and height for ratio and max

- composer.json
Resolve #71 
Fix invalid composer replace.
Use underscores in package name.
> Issue 71 fix composer

- Classes/Controller/SelectImageController.php
TYPO3 Deprecation Notice: There is a reference to "EXT:lang/Resources/Private/Language/locallang_core.xlf", which has been moved to "EXT:core/Resources/Private/Language/locallang_core.xlf". This fallback will be removed with TYPO3 v10.0.
> Fix deprecation log about locallang_core.xlf

- Resources/Public/JavaScript/Plugins/typo3image.js
When html loaded from a field is not wrapped on a single dom node js fails on line 30:
`$shadowEditor = $(editor.element.$.innerText),`
Forcing a wrap of the innerText value solves it:
`$shadowEditor = $("<div>").append(editor.element.$.innerText),`
> [TASK] Wrapping innerText to avoid js error

- Resources/Public/JavaScript/Plugins/typo3image.js
Rarely, ckeditor is not loaded if jQuery is not present at typo3image plugin init time.
> [TASK] guard clause if jQuery is not present

- Configuration/TypoScript/ImageRendering/setup.txt
Reverts netresearch/t3x-rte_ckeditor_image#116
Images won't be rendered any more by 
Netresearch\RteCKEditorImage\Controller\ImageRenderingController->renderImageAttributes
> Revert "[BUGFIX] use parseFunc_RTE for processing"

- Resources/Public/JavaScript/Plugins/typo3image.js
Related to https://github.com/netresearch/t3x-rte_ckeditor_image/issues/103
I stumbled over rte missing on translated records if they had the prefix "[Translate to <lang>:]" earlier using EXT:tt_news. However as I couldn't find anything and no relation to this ext and just removed that prefix from the database and creation of new records.
However now I stumbled upon a missing RTE field for a news entry without anything like that, but still having an old `<a target="_blank" class="external-link-new-window"` in the bodytext, but even after removing that the RTE wasn't rendered with `Uncaught Error: Syntax error, unrecognized expression`. I couldn't find the reason, the text in that case just had some umlauts and `<strong>` tags (one empty) but nothing suspicious.
The mentioned change in …
> [BUGFIX] Implement hotfix from #103

- Classes/Database/RteImagesDbHook.php
If a file that is resolved by its path is a processed file the uid must be resolved correctly.
This implements following todo from the source sode:
"@todo if the retrieved file is a processed file, get the original file..."
> Resolve retrieved file correctly if its a processed file

- Configuration/TCA/Overrides/sys_template.php
- Configuration/TypoScript/ImageRendering/setup.txt
- README.md
- ext_localconf.php
RTE Images within links shouldn't be wrapped by an p tag, that's not valid HTML.
One solution is to disable it via TypoScript Setup.
Therefore the order of including the static TS file must be customizable.
Fixes #112
> WIP: [BUGFIX] #112: Remove wrapping p-tag from images via TS

- Classes/Database/RteImagesDbHook.php
- composer.json
- ext_emconf.php
Fixed img src generation on first save of RTE, changed TYPO3 version constraints (fixes #126 and #142)
> [BUGFIX] #126 Wrong link in image, #142 Wrong backwards compatibility

- Resources/Public/JavaScript/Plugins/typo3image.js
Solution is parsing of every toolbars, then checking if the command is
'image'. If yes, put the button state at 'off' since button.getState
returns undefined
Fixes  netresearch/t3x-rte_ckeditor_image #145
> [bugfix/145]Fix disabled button. Fixes netresearch/t3x-rte_ckeditor_image #145

- Resources/Public/JavaScript/Plugins/typo3image.js
Solution is parsing of every toolbars, then checking if the command is
'image'. If yes, put the button state at 'off' since button.getState
returns undefined
> [bugfix/145]Fix disabled button.

- Classes/Controller/ImageLinkRenderingController.php
- Classes/Controller/ImageRenderingController.php
- Classes/Controller/SelectImageController.php
- Classes/Database/RteImagesDbHook.php
- Classes/Database/RteImagesSoftReferenceIndex.php
- composer.json
- ext_emconf.php
- phpstan.neon
This pull request fixed invalid PHP/PHPDoc syntax, adds missing functionality which has been deprecated and already removed from TYPO3 core, and prevents some undetected bugs.
It is based on PR #153, since the errors fixed in there would also have been reported by PHPStan.
All error levels have been fixed in individual commits.
There are still 19 more errors on level 9, but fixing them is mostly adding them to the exclusion list, since TYPO3 core type annotations are not yet as perfect as they could be.
> Make extension PHPStan level 8 error-free

- Classes/Database/RteImagesDbHook.php
The fetching of an external file with GeneralUtility::getUrl() may throw an exception if the image is not available (at least since Guzzle is used internally with TYPO3 and libcurl is installed).
The exception is now caught. If the exception occurs no further processing on the image is done.
Resolves: #190
> [BUGFIX] Catch exception when fetching external image

- Classes/Controller/ImageRenderingController.php
this fixes #187
The situation is as follows: starting with 11LTS in the backend processed images get not a `/fileaadmin/_processed/` "resulting image" style url but a new `/typo3/image/process?token` "middleware" style url. However that is only available for logged in BE users. Thus this can be saved to RTE and displayed there, however will break the frontend output.
Now I tried to fix what is saved in the backend/db, but came to the conclusion that this shouldn't be the aim, as there are probably reasons for the backend using that new URL.
Thus my approach here is to accept this new URL, accept the "bug" that this new URL gets converted to an absolute URL and rather tackle the problem while generating frontend output, where the generation is skipped formerly, because it sees "external …
> [BUGFIX] fix misuse of 11LTS BE processing middleware URLs

- Classes/Database/RteImagesDbHook.php
This prevents a "undefined array key" error in php 8 when saving the ContentElement in the backend.
---
Related #152
> [BUGFIX] Prevent undefined array key

- Classes/Controller/ImageRenderingController.php
- Classes/Controller/SelectImageController.php
After switching to 11LTS I saw an issue: 
Some old RTE fields (last change >=5 years) exist which were never properly converted, so using `<img src="fileadmin/..."/>` (no slash prefix, no data attributes) instead of `<img src="/fileadmin/..." data-htmlarea-file-uid=.../>`. While in 10LTS they were rendered correctly, in 11LTS they are not processed, keeping the version without a slash, thus not working on subpages.
Diving into the code the `SelectImageController` as well as the `ImageRenderingController` use different approaches to manipulate the src. I propose to simplify this. The idea is basically: as long as it is no external URL, it should start with a slash, instead of allowing `fileadmin` without slash in frontend or force-prefixing a FQDN in backend RTE.
I wonder if that has …
> [BUGFIX] fileadmin path without slash won't output in 11LTS

- Classes/Database/RteImagesDbHook.php
Couldn't reproduce the issue on my system, but added an additional `isset` to the if condition to check if the array element is declared or not.
> #205: Fix PHP warning about undefined array key access

- Resources/Public/JavaScript/Plugins/typo3image.js
On TYPO3v3 images aren't loaded in editor after inserting.
There is just a white Placeholder, the image is loaded after saving or switching to code view.
This is a fix for images stored on public and non public filestorages.
> Load Image when inserted to editor

- Classes/Controller/ImageRenderingController.php
**Explain the details**
When the alt- or title-attribute is overriden, a data attribute like data-title-override with the value true is added to the img tag in the editor. While outputting the image this value was used instead of the entered value, which caused the alt- and title-attributes to contain the value "true" in the frontend.
**Closing issues**
Closes #224
> Fix output of alt and title attribute when overriden

- .gitattributes
When packaging the extension or installing via Composer, development files such as .editorconfig or Tests should be excluded.
The .gitattributes file added contains some files not in this project - this makes it easier to maintain: even if files are added later, it is not always necessary to change .gitattributes
Resolves: #230
> Add .attributes

- Classes/Controller/ImageRenderingController.php
- Classes/Database/RteImagesDbHook.php
Handles 2 related problems:
1. If images contain an embedded image (beginning with data:image) and not  a path, a slash should not be prepended. Otherwise this breaks the rendering.
2. Do not prepend the site URL to embedded image in RTE pre-processing hook (when loading from DB to RTE)
Resolves: #226
Resolves: #228
> Correctly handle embedded images (data:image)

- .github/workflows/phpstan.yml
- .github/workflows/testing.yml
- .gitignore
- Build/Scripts/ci.sh
- Build/Scripts/cleanup.sh
- Build/Scripts/runTests.sh
- Build/phpunit/FunctionalTests.xml
- Build/phpunit/FunctionalTestsBootstrap.php
- Build/phpunit/UnitTests.xml
- Build/phpunit/UnitTestsBootstrap.php
- Build/testing-docker/docker-compose.yml
- Classes/DataHandling/SoftReference/RteImageSoftReferenceParser.php
- Tests/Functional/DataHandling/Fixtures/ReferenceIndex/UpdateReferenceIndexImport.csv
- Tests/Functional/DataHandling/Fixtures/ReferenceIndex/UpdateReferenceIndexResult.csv
- Tests/Functional/DataHandling/RteImageSoftReferenceParserTest.php
- composer.json
- phpstan.neon
**Note** (not in commit): main goal here is to add a fix and one functional test to check. I have used the procedure with runTests.sh as documented in [TYPO3 Explained "Extension Testing"](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/ExtensionTesting.html).
If a different procedure should be used to execute the functional tests, I would be happy to make the necessary changes to this PR (easiest would be to point to an example extension which can be used as blueprint).
---------------------
Fix RteImageSoftReferenceParser
The reference index entry was previously not created, because
a SoftReferenceParserResult was created with the wrong format.
Resolves: #45
--------------------
Add functional tests
- add .gitattributes
- set web-dir to .Build/Web in composer.json
- …
> Fix issue that reference index is not created for image soft references

- Resources/Public/JavaScript/Plugins/typo3image.js
The problem is that when you open the plugin, aka click on the image module in the RTE, the currently viewed images are provided with an event listner that inserts the image when clicked. However, if you change to another folder in the Fileadmin, the other images have to be reloaded and thus replace the images in the Dom - these then have no "onClick" method.
The result is that images are no longer inserted and the popup with the image properties does not appear. If you open the image plugin again, the just viewed images get the onClick method and work as expected.
Therefore I wrote an observer for the filelist and on change it readds the images to
AddImage.elements and adds the event listner.
Related: #238
> [BUGFIX] Fix onclick event for select image modal

- Classes/Database/RteImagesDbHook.php
Dynamic properties are deprecated as of PHP 8.2.0. Either properties have to be declared or a class has to be marked with the `#[\AllowDynamicProperties]` attribute.
Closes #235
> [BUGFIX] Loading RTE throws PHP Runtime Deprecation Notice

- Classes/Backend/Preview/RteImagePreviewRenderer.php
- Classes/Controller/ImageLinkRenderingController.php
- Classes/Database/RteImagesDbHook.php
- Tests/Functional/DataHandling/RteImageSoftReferenceParserTest.php
Fix current build/test pipeline/actions.
- style: phpstan error "Offset 'data-htmlarea-file…' on non-empty-array<string, string> on left side of ?? always exists and is not nullable." by removing superfluous null check.
- tests: fix PHP Fatal error: Type of testExtensionsToLoad must be array
- style: fix superfluous space before closing parenthesis
> chore: Fix current build/tests in pipeline/actions.

- Classes/Database/RteImagesDbHook.php
This change simply catches the exception TYPO3 may throw when trying to retrieve a already deleted file.
fixes #254
> [BUGFIX] Fixes #254: handle deleted files
